from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class OrochiAssets: 


	# Image Rule Assets
	# 八级大蛇进入 
	I_OROCHI = RuleImage(roi_front=(297,86,50,260), roi_back=(297,86,50,260), threshold=0.8, method="Template matching", file="./tasks/Orochi/o/o_orochi.png")
	# 组队 
	I_FORM_TEAM = RuleImage(roi_front=(964,605,95,46), roi_back=(964,605,95,46), threshold=0.8, method="Template matching", file="./tasks/Orochi/o/o_form_team.png")
	# description 
	I_OROCHI_LOCK = RuleImage(roi_front=(652,654,21,32), roi_back=(652,654,21,32), threshold=0.8, method="Template matching", file="./tasks/Orochi/o/o_orochi_lock.png")
	# description 
	I_OROCHI_UNLOCK = RuleImage(roi_front=(653,657,20,24), roi_back=(653,657,20,24), threshold=0.8, method="Template matching", file="./tasks/Orochi/o/o_orochi_unlock.png")
	# 点击挑战 
	I_OROCHI_FIRE = RuleImage(roi_front=(1149,595,84,45), roi_back=(1149,595,84,45), threshold=0.6, method="Template matching", file="./tasks/Orochi/o/o_orochi_fire.png")
	# 式神录 
	I_SHI_RECORDS = RuleImage(roi_front=(848,570,37,41), roi_back=(848,570,37,41), threshold=0.8, method="Template matching", file="./tasks/Orochi/o/o_shi_records.png")
	# 小小宠物，发现宝藏 
	I_PET_PRESENT = RuleImage(roi_front=(873,184,62,147), roi_back=(873,184,62,147), threshold=0.8, method="Template matching", file="./tasks/Orochi/o/o_pet_present.png")


	# List Rule Assets
	# 这个是御魂界面选择不同层数的 
	L_LAYER_LIST = RuleList(folder="./tasks/Orochi/res", direction="vertical", mode="ocr", roi_back=(138,130,359,500), size=(45, 88), 
					 array=["壹", "贰", "叁", "肆", "伍", "陆", "柒", "捌", "玖", "拾", "悲", "神", "虚"])


	# Ocr Rule Assets
	# Ocr-description 
	O_O_TEST_OCR = RuleOcr(roi=(126,136,360,491), area=(126,136,360,491), mode="Full", method="Default", keyword="", name="o_test_ocr")


